import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import "../globals.css";
import { getMessages } from 'next-intl/server';
import Navbar from '@/components/shared/navbar';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await getMessages();
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        dir={locale === "ar" ? "rtl" : "ltr"}
        className={` antialiased`}
      >
        <NextIntlClientProvider messages={messages} locale={locale} >
          <Navbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
